import { lazy, type ComponentType } from 'react'

export interface ToolDef {
  id: string
  category: string
  title: string
  description: string
  keywords: string[]
  component: ReturnType<typeof lazy<ComponentType>>
}

export const tools: ToolDef[] = [
  {
    id: 'color-converter',
    category: 'Colors',
    title: 'Color Converter',
    description:
      'Convert any color between HEX, RGB, RGBA, HSL, HSB, CMYK, and more. Includes live sliders, shade/tint palette, and one-click copy for every format.',
    keywords: [
      'color',
      'hex',
      'rgb',
      'hsl',
      'hsb',
      'hsv',
      'cmyk',
      'converter',
      'palette',
      'picker',
      'css',
      'tailwind',
    ],
    component: lazy(() => import('./colors/color-converter/index')),
  },
  {
    id: 'pizza-dough',
    category: 'Food',
    title: 'Pizza Dough Calculator',
    description:
      'Calculate exact ingredient amounts for homemade pizza dough. Supports thin, regular, and thick crust; gluten-free option included.',
    keywords: ['pizza', 'dough', 'recipe', 'flour', 'baking', 'food', 'ingredients'],
    component: lazy(() => import('./food/pizza-dough/index')),
  },
  {
    id: 'pepperoni-rolls',
    category: 'Food',
    title: 'Pepperoni Rolls Calculator',
    description:
      "Calculate exact ingredient amounts for homemade pepperoni roll dough using baker's percentages. Bakes at 475°F for 12 minutes; brush with garlic butter after.",
    keywords: [
      'pepperoni',
      'rolls',
      'bread',
      'dough',
      'recipe',
      'flour',
      'baking',
      'food',
      'ingredients',
      'garlic butter',
    ],
    component: lazy(() => import('./food/pepperoni-rolls/index')),
  },
  {
    id: 'markdown-editor',
    category: 'Writing',
    title: 'Markdown Editor',
    description:
      'Distraction-free markdown editor for LLM prompts and docs. Live preview, per-document undo history, real-time token counts (GPT-4o exact; Claude/Gemini estimated), and multi-document management — all saved locally.',
    keywords: [
      'markdown',
      'editor',
      'llm',
      'prompt',
      'writing',
      'tokens',
      'preview',
      'gpt',
      'claude',
      'gemini',
      'notes',
      'docs',
    ],
    component: lazy(() => import('./writing/markdown-editor/index')),
  },
  {
    id: 'base64-encoder',
    category: 'Developer',
    title: 'Base64 Encoder / Decoder',
    description:
      'Encode plain text to Base64 or decode Base64 back to text — fully Unicode-safe (emoji, accented chars, CJK all supported). Supports standard Base64 and Base64URL variants. Includes a file → data URI converter with drag-and-drop.',
    keywords: [
      'base64',
      'encode',
      'decode',
      'base64url',
      'data uri',
      'data url',
      'binary',
      'unicode',
      'text',
      'converter',
      'file',
      'image',
      'btoa',
      'atob',
    ],
    component: lazy(() => import('./developer/base64-encoder/index')),
  },
  {
    id: 'json-formatter',
    category: 'Developer',
    title: 'JSON Formatter',
    description:
      'Edit, format, and validate JSON. Prettify with configurable indent (2, 4, or tab), minify to a single line, sort keys alphabetically, and see live parse errors with line and column numbers.',
    keywords: [
      'json',
      'formatter',
      'beautify',
      'prettify',
      'minify',
      'validate',
      'lint',
      'format',
      'pretty print',
      'indent',
      'sort keys',
      'editor',
    ],
    component: lazy(() => import('./developer/json-formatter/index')),
  },
  {
    id: 'string-escaper',
    category: 'Developer',
    title: 'String Escaper',
    description:
      'Convert strings between escaped (JSON/code-safe) and readable form. Handles \\n, \\t, \\r, \\", \\\\, \\uXXXX, and surrogate pairs. Handy for decoding JSON-encoded strings with embedded escape sequences.',
    keywords: [
      'escape',
      'unescape',
      'string',
      'json',
      'encode',
      'decode',
      'newline',
      'unicode',
      'surrogate',
      'backslash',
      'special characters',
      'text',
    ],
    component: lazy(() => import('./developer/string-escaper/index')),
  },
  {
    id: 'jwt-decoder',
    category: 'Developer',
    title: 'JWT Decoder',
    description:
      'Decode and inspect JSON Web Tokens client-side — nothing is sent to any server. View header, payload claims, and signature. Standard claims (iat, exp, nbf) are shown as readable dates with expired-token highlighting.',
    keywords: [
      'jwt',
      'token',
      'decode',
      'base64',
      'base64url',
      'json web token',
      'header',
      'payload',
      'claims',
      'iat',
      'exp',
      'nbf',
      'auth',
      'authentication',
    ],
    component: lazy(() => import('./developer/jwt-decoder/index')),
  },
  {
    id: 'uuid-generator',
    category: 'Developer',
    title: 'UUID / ULID Generator',
    description:
      'Generate UUID v4, UUID v7, ULID, and Nano ID identifiers. Bulk generation up to 1000 at once, with formatting options (uppercase/lowercase, with/without hyphens). All IDs generated client-side using crypto.getRandomValues.',
    keywords: [
      'uuid',
      'guid',
      'ulid',
      'nanoid',
      'nano id',
      'v4',
      'v7',
      'identifier',
      'random',
      'generator',
      'unique',
      'id',
      'rfc9562',
      'crockford',
      'base32',
      'timestamp',
    ],
    component: lazy(() => import('./developer/uuid-generator/index')),
  },
  {
    id: 'hash-generator',
    category: 'Developer',
    title: 'Hash Generator',
    description:
      'Hash text or files client-side with MD5, SHA-1, SHA-256, SHA-384, and SHA-512. All algorithms shown at once with one-click copy. Supports uppercase/lowercase hex and Base64 output. Optional HMAC mode for SHA algorithms. File drag-and-drop supported.',
    keywords: [
      'hash',
      'md5',
      'sha',
      'sha1',
      'sha256',
      'sha384',
      'sha512',
      'checksum',
      'digest',
      'hmac',
      'integrity',
      'crypto',
      'base64',
      'hex',
      'file hash',
      'webcrypto',
    ],
    component: lazy(() => import('./developer/hash-generator/index')),
  },
  {
    id: 'diff-viewer',
    category: 'Developer',
    title: 'Diff Viewer',
    description:
      'Compare two pieces of text line-by-line. Highlights additions in green and deletions in red, with intraline (word/character-level) highlights for changed pairs. Toggle between unified and side-by-side views. Options to ignore whitespace and case.',
    keywords: [
      'diff',
      'compare',
      'text compare',
      'difference',
      'patch',
      'side by side',
      'unified',
      'line diff',
      'text diff',
      'changes',
      'additions',
      'deletions',
      'file diff',
      'code diff',
      'merge',
      'myers',
      'developer',
    ],
    component: lazy(() => import('./developer/diff-viewer/index')),
  },
  {
    id: 'regex-tester',
    category: 'Developer',
    title: 'Regex Tester',
    description:
      'Test and debug regular expressions live. Highlights matches in your test string with alternating colours, lists every match with its capture groups, and previews .replace() output. Includes a library of common patterns (email, URL, UUID, IPv4, hex colour, and more).',
    keywords: [
      'regex',
      'regexp',
      'regular expression',
      'match',
      'test',
      'capture group',
      'pattern',
      'replace',
      'flags',
      'global',
      'multiline',
      'unicode',
      'named group',
      'highlight',
      'email',
      'url',
      'ipv4',
      'uuid',
      'developer',
      'debug',
    ],
    component: lazy(() => import('./developer/regex-tester/index')),
  },
  {
    id: 'llano-castell',
    category: 'Rivers',
    title: 'Llano River @ Castell',
    description:
      'Trip planner for Kevin\'s annual Castell fishing trip. Live USGS gauge data, Castell flow estimate (no gauge there — interpolated via DAR), per-day forecast, wading verdict, and 10-year history chart.',
    keywords: [
      'llano',
      'river',
      'texas',
      'usgs',
      'gauge',
      'cfs',
      'water level',
      'castell',
      'fishing',
      'wading',
      'forecast',
      'recession',
    ],
    component: lazy(() => import('./rivers/llano-castell/index')),
  },
]

/** Unique categories in display order */
export const categories = [...new Set(tools.map((t) => t.category))]

/** Look up a tool by id */
export function getToolById(id: string): ToolDef | undefined {
  return tools.find((t) => t.id === id)
}
