import { lazy, type ComponentType } from 'react'

export interface ToolDef {
  id: string
  category: string
  title: string
  description: string
  keywords: string[]
  component: ReturnType<typeof lazy<ComponentType>>
}

export const tools: ToolDef[] = [
  {
    id: 'word-counter',
    category: 'Text',
    title: 'Word & Character Counter',
    description:
      'Live word, character, sentence, paragraph, and line counts. Reading and speaking time estimates. ' +
      'Top-10 word frequency table with stopword filter. Copy a plain-text stats summary in one click.',
    keywords: [
      'word count',
      'character count',
      'counter',
      'text',
      'statistics',
      'reading time',
      'speaking time',
      'sentences',
      'paragraphs',
      'lines',
      'frequency',
      'word frequency',
      'stopwords',
      'letters',
      'digits',
      'punctuation',
      'whitespace',
      'unicode',
      'wpm',
      'text analysis',
    ],
    component: lazy(() => import('./text/word-counter/index')),
  },
  {
    id: 'case-converter',
    category: 'Text',
    title: 'Case Converter',
    description:
      'Convert text between 14 case styles at once: camelCase, PascalCase, snake_case, ' +
      'SCREAMING_SNAKE_CASE, kebab-case, Train-Case, dot.case, path/case, Title Case, ' +
      'Sentence case, lowercase, UPPERCASE, aLtErNaTiNg CaSe, and InVeRsE cAsE. ' +
      'Robust tokenizer handles camelCase/PascalCase boundaries, acronyms, digits, and mixed separators. ' +
      'Paste multiple lines to convert each identifier independently.',
    keywords: [
      'case',
      'convert',
      'converter',
      'camelcase',
      'camel case',
      'pascal case',
      'pascalcase',
      'snake case',
      'snake_case',
      'screaming snake case',
      'kebab case',
      'kebab-case',
      'train case',
      'dot case',
      'path case',
      'title case',
      'sentence case',
      'uppercase',
      'lowercase',
      'alternating case',
      'inverse case',
      'swap case',
      'rename',
      'identifier',
      'variable',
      'naming convention',
      'programming',
      'text transform',
      'format',
    ],
    component: lazy(() => import('./text/case-converter/index')),
  },
  {
    id: 'lorem-ipsum',
    category: 'Text',
    title: 'Lorem Ipsum Generator',
    description:
      'Generate placeholder text by paragraphs, sentences, or words using the traditional lorem ipsum word list. ' +
      'Options for the classic "Lorem ipsum dolor sit amet…" opening and plain text or HTML output formats.',
    keywords: [
      'lorem',
      'ipsum',
      'placeholder',
      'dummy text',
      'filler',
      'filler text',
      'generator',
      'paragraphs',
      'sentences',
      'words',
      'mockup',
      'prototype',
      'latin',
      'sample text',
      'placeholder text',
      'boilerplate',
      'text generator',
      'design',
      'wireframe',
    ],
    component: lazy(() => import('./text/lorem-ipsum/index')),
  },
  {
    id: 'qr-generator',
    category: 'Everyday',
    title: 'QR Code Generator',
    description:
      'Generate QR codes for plain text, URLs, WiFi credentials, vCard contacts, email (mailto:), ' +
      'SMS, phone numbers, and geographic coordinates. Live preview, SVG and PNG downloads, ' +
      'adjustable error correction, colors, and margin. Everything runs in your browser.',
    keywords: [
      'qr',
      'qr code',
      'generator',
      'barcode',
      'wifi',
      'password',
      'vcard',
      'contact',
      'url',
      'link',
      'email',
      'mailto',
      'sms',
      'text message',
      'phone',
      'geo',
      'location',
      'coordinates',
      'png',
      'svg',
      'download',
      'scan',
      'scanner',
      'encode',
    ],
    component: lazy(() => import('./everyday/qr-generator/index')),
  },
  {
    id: 'bill-splitter',
    category: 'Everyday',
    title: 'Tip & Bill Splitter',
    description:
      'Calculate tip and split the bill among any number of people. ' +
      'Quick-pick tip buttons (10/15/18/20/25%), custom tip with slider, optional tax with pre-tax tipping, ' +
      'and round-up to nearest 50¢ or $1. Fair split using largest-remainder — per-person amounts differ by at most 1¢.',
    keywords: [
      'tip',
      'bill',
      'split',
      'splitter',
      'restaurant',
      'gratuity',
      'calculator',
      'per person',
      'tax',
      'tip calculator',
      'bill splitter',
      'dining',
      'dinner',
      'share',
      'divide',
      'group',
      'party',
      'check',
      'receipt',
      'percentage',
      'money',
      'round up',
    ],
    component: lazy(() => import('./everyday/bill-splitter/index')),
  },
  {
    id: 'unit-converter',
    category: 'Converters',
    title: 'Unit Converter',
    description:
      'Convert between units of length, weight/mass, temperature, volume, area, speed, and data. ' +
      'Live conversion, swap button, all-units table, and absolute-zero warnings for temperature.',
    keywords: [
      'unit',
      'convert',
      'converter',
      'metric',
      'imperial',
      'length',
      'weight',
      'mass',
      'temperature',
      'volume',
      'area',
      'speed',
      'data',
      'celsius',
      'fahrenheit',
      'kelvin',
      'mm',
      'cm',
      'km',
      'meter',
      'metre',
      'inch',
      'foot',
      'feet',
      'mile',
      'gram',
      'kilogram',
      'pound',
      'ounce',
      'litre',
      'liter',
      'gallon',
      'mph',
      'kph',
      'byte',
      'gigabyte',
      'megabyte',
      'kilobyte',
    ],
    component: lazy(() => import('./converters/unit-converter/index')),
  },
  {
    id: 'color-converter',
    category: 'Colors',
    title: 'Color Converter',
    description:
      'Convert any color between HEX, RGB, RGBA, HSL, HSB, CMYK, and more. Includes live sliders, shade/tint palette, and one-click copy for every format.',
    keywords: [
      'color',
      'hex',
      'rgb',
      'hsl',
      'hsb',
      'hsv',
      'cmyk',
      'converter',
      'palette',
      'picker',
      'css',
      'tailwind',
    ],
    component: lazy(() => import('./colors/color-converter/index')),
  },
  {
    id: 'pizza-dough',
    category: 'Food',
    title: 'Pizza Dough Calculator',
    description:
      'Calculate exact ingredient amounts for homemade pizza dough. Supports thin, regular, and thick crust; gluten-free option included.',
    keywords: ['pizza', 'dough', 'recipe', 'flour', 'baking', 'food', 'ingredients'],
    component: lazy(() => import('./food/pizza-dough/index')),
  },
  {
    id: 'pepperoni-rolls',
    category: 'Food',
    title: 'Pepperoni Rolls Calculator',
    description:
      "Calculate exact ingredient amounts for homemade pepperoni roll dough using baker's percentages. Bakes at 475°F for 12 minutes; brush with garlic butter after.",
    keywords: [
      'pepperoni',
      'rolls',
      'bread',
      'dough',
      'recipe',
      'flour',
      'baking',
      'food',
      'ingredients',
      'garlic butter',
    ],
    component: lazy(() => import('./food/pepperoni-rolls/index')),
  },
  {
    id: 'markdown-editor',
    category: 'Writing',
    title: 'Markdown Editor',
    description:
      'Distraction-free markdown editor for LLM prompts and docs. Live preview, per-document undo history, real-time token counts (GPT-4o exact; Claude/Gemini estimated), and multi-document management — all saved locally.',
    keywords: [
      'markdown',
      'editor',
      'llm',
      'prompt',
      'writing',
      'tokens',
      'preview',
      'gpt',
      'claude',
      'gemini',
      'notes',
      'docs',
    ],
    component: lazy(() => import('./writing/markdown-editor/index')),
  },
  {
    id: 'base64-encoder',
    category: 'Developer',
    title: 'Base64 Encoder / Decoder',
    description:
      'Encode plain text to Base64 or decode Base64 back to text — fully Unicode-safe (emoji, accented chars, CJK all supported). Supports standard Base64 and Base64URL variants. Includes a file → data URI converter with drag-and-drop.',
    keywords: [
      'base64',
      'encode',
      'decode',
      'base64url',
      'data uri',
      'data url',
      'binary',
      'unicode',
      'text',
      'converter',
      'file',
      'image',
      'btoa',
      'atob',
    ],
    component: lazy(() => import('./developer/base64-encoder/index')),
  },
  {
    id: 'json-formatter',
    category: 'Developer',
    title: 'JSON Formatter',
    description:
      'Edit, format, and validate JSON. Prettify with configurable indent (2, 4, or tab), minify to a single line, sort keys alphabetically, and see live parse errors with line and column numbers.',
    keywords: [
      'json',
      'formatter',
      'beautify',
      'prettify',
      'minify',
      'validate',
      'lint',
      'format',
      'pretty print',
      'indent',
      'sort keys',
      'editor',
    ],
    component: lazy(() => import('./developer/json-formatter/index')),
  },
  {
    id: 'string-escaper',
    category: 'Developer',
    title: 'String Escaper',
    description:
      'Convert strings between escaped (JSON/code-safe) and readable form. Handles \\n, \\t, \\r, \\", \\\\, \\uXXXX, and surrogate pairs. Handy for decoding JSON-encoded strings with embedded escape sequences.',
    keywords: [
      'escape',
      'unescape',
      'string',
      'json',
      'encode',
      'decode',
      'newline',
      'unicode',
      'surrogate',
      'backslash',
      'special characters',
      'text',
    ],
    component: lazy(() => import('./developer/string-escaper/index')),
  },
  {
    id: 'jwt-decoder',
    category: 'Developer',
    title: 'JWT Decoder',
    description:
      'Decode and inspect JSON Web Tokens client-side — nothing is sent to any server. View header, payload claims, and signature. Standard claims (iat, exp, nbf) are shown as readable dates with expired-token highlighting.',
    keywords: [
      'jwt',
      'token',
      'decode',
      'base64',
      'base64url',
      'json web token',
      'header',
      'payload',
      'claims',
      'iat',
      'exp',
      'nbf',
      'auth',
      'authentication',
    ],
    component: lazy(() => import('./developer/jwt-decoder/index')),
  },
  {
    id: 'uuid-generator',
    category: 'Developer',
    title: 'UUID / ULID Generator',
    description:
      'Generate UUID v4, UUID v7, ULID, and Nano ID identifiers. Bulk generation up to 1000 at once, with formatting options (uppercase/lowercase, with/without hyphens). All IDs generated client-side using crypto.getRandomValues.',
    keywords: [
      'uuid',
      'guid',
      'ulid',
      'nanoid',
      'nano id',
      'v4',
      'v7',
      'identifier',
      'random',
      'generator',
      'unique',
      'id',
      'rfc9562',
      'crockford',
      'base32',
      'timestamp',
    ],
    component: lazy(() => import('./developer/uuid-generator/index')),
  },
  {
    id: 'hash-generator',
    category: 'Developer',
    title: 'Hash Generator',
    description:
      'Hash text or files client-side with MD5, SHA-1, SHA-256, SHA-384, and SHA-512. All algorithms shown at once with one-click copy. Supports uppercase/lowercase hex and Base64 output. Optional HMAC mode for SHA algorithms. File drag-and-drop supported.',
    keywords: [
      'hash',
      'md5',
      'sha',
      'sha1',
      'sha256',
      'sha384',
      'sha512',
      'checksum',
      'digest',
      'hmac',
      'integrity',
      'crypto',
      'base64',
      'hex',
      'file hash',
      'webcrypto',
    ],
    component: lazy(() => import('./developer/hash-generator/index')),
  },
  {
    id: 'diff-viewer',
    category: 'Developer',
    title: 'Diff Viewer',
    description:
      'Compare two pieces of text line-by-line. Highlights additions in green and deletions in red, with intraline (word/character-level) highlights for changed pairs. Toggle between unified and side-by-side views. Options to ignore whitespace and case.',
    keywords: [
      'diff',
      'compare',
      'text compare',
      'difference',
      'patch',
      'side by side',
      'unified',
      'line diff',
      'text diff',
      'changes',
      'additions',
      'deletions',
      'file diff',
      'code diff',
      'merge',
      'myers',
      'developer',
    ],
    component: lazy(() => import('./developer/diff-viewer/index')),
  },
  {
    id: 'regex-tester',
    category: 'Developer',
    title: 'Regex Tester',
    description:
      'Test and debug regular expressions live. Highlights matches in your test string with alternating colours, lists every match with its capture groups, and previews .replace() output. Includes a library of common patterns (email, URL, UUID, IPv4, hex colour, and more).',
    keywords: [
      'regex',
      'regexp',
      'regular expression',
      'match',
      'test',
      'capture group',
      'pattern',
      'replace',
      'flags',
      'global',
      'multiline',
      'unicode',
      'named group',
      'highlight',
      'email',
      'url',
      'ipv4',
      'uuid',
      'developer',
      'debug',
    ],
    component: lazy(() => import('./developer/regex-tester/index')),
  },
  {
    id: 'url-parser',
    category: 'Developer',
    title: 'URL Parser / Encoder',
    description:
      'Inspect every part of a URL — protocol, auth, host, port, path, query string, and fragment. Edit query parameters live and see the reconstructed URL update instantly. Includes an encode/decode section for encodeURIComponent, decodeURIComponent, encodeURI, and decodeURI.',
    keywords: [
      'url',
      'uri',
      'parse',
      'query string',
      'query params',
      'search params',
      'encode',
      'decode',
      'percent encoding',
      'urlencode',
      'urldecode',
      'encodeURIComponent',
      'decodeURIComponent',
      'encodeURI',
      'decodeURI',
      'host',
      'hostname',
      'port',
      'pathname',
      'fragment',
      'hash',
      'protocol',
      'developer',
    ],
    component: lazy(() => import('./developer/url-parser/index')),
  },
  {
    id: 'cron-parser',
    category: 'Developer',
    title: 'Cron Expression Parser',
    description:
      'Parse and preview cron schedules in plain English. Shows the next 10 run times, a per-field breakdown, and supports all standard syntax — wildcards, ranges, steps, lists, month/day names, and macros like @daily.',
    keywords: [
      'cron',
      'crontab',
      'schedule',
      'expression',
      'parser',
      'next run',
      'scheduler',
      'interval',
      'recurring',
      'job',
      'task',
      'timing',
      'minute',
      'hour',
      'daily',
      'weekly',
      'monthly',
      'cronjob',
      'unix',
      'linux',
      'developer',
    ],
    component: lazy(() => import('./developer/cron-parser/index')),
  },
  {
    id: 'timezone-planner',
    category: 'Time',
    title: 'Timezone Meeting Planner',
    description:
      'Plan meetings across multiple timezones. Visual 24-hour strip shows working, shoulder, and night hours for each location. Highlights when all zones overlap in working hours (or the best compromise). DST-aware — offsets are derived from the selected date, not fixed.',
    keywords: [
      'timezone',
      'meeting',
      'planner',
      'world clock',
      'working hours',
      'overlap',
      'utc',
      'cities',
      'schedule',
      'dst',
      'daylight saving',
      'time zones',
      'international',
      'collaboration',
      'remote',
      'team',
      'time difference',
      'time converter',
    ],
    component: lazy(() => import('./time/timezone-planner/index')),
  },
  {
    id: 'date-calculator',
    category: 'Time',
    title: 'Date Calculator',
    description:
      'Days between two dates with year/month/day breakdown, weeks, and business days. ' +
      'Add or subtract days, weeks, months, years, or business days from any date with correct month-end clamping. ' +
      'Age calculator with next-birthday countdown. Live countdown timer to any target date or datetime.',
    keywords: [
      'date',
      'calculator',
      'days between',
      'date difference',
      'countdown',
      'age',
      'age calculator',
      'birthday',
      'next birthday',
      'business days',
      'working days',
      'add days',
      'subtract days',
      'add months',
      'duration',
      'calendar',
      'date math',
      'how many days',
      'days until',
      'days since',
      'date range',
      'weekdays',
    ],
    component: lazy(() => import('./time/date-calculator/index')),
  },
  {
    id: 'timestamp-converter',
    category: 'Time',
    title: 'Unix Timestamp Converter',
    description:
      'Convert Unix timestamps to human-readable dates and back. Auto-detects seconds, milliseconds, and microseconds. Shows local time, UTC, ISO 8601, relative time ("3 hours ago"), and world clocks for major timezones.',
    keywords: [
      'unix',
      'timestamp',
      'epoch',
      'time',
      'date',
      'converter',
      'milliseconds',
      'microseconds',
      'seconds',
      'iso 8601',
      'utc',
      'timezone',
      'unix time',
      'unix epoch',
      'posix time',
      'datetime',
      'date converter',
      'time converter',
      'relative time',
      'world clock',
    ],
    component: lazy(() => import('./time/timestamp-converter/index')),
  },
  {
    id: 'visual-markdown-editor',
    category: 'Writing',
    title: 'Visual Markdown Editor',
    description:
      'WYSIWYG markdown editor for non-technical users. Four modes: Visual (rich-text), Markdown (source), Preview, and Split (live side-by-side). ' +
      'Gravity-UI-style formatting toolbar, floating selection toolbar, / slash command menu, tables with hover row/column handles, task lists, and multi-document support. ' +
      'Error-safe: visual editor crashes fall back to Markdown mode automatically. All editing stays in-browser — no uploads, no server.',
    keywords: [
      'wysiwyg',
      'markdown',
      'visual',
      'editor',
      'rich text',
      'no-code',
      'writing',
      'document',
      'formatting',
      'bold',
      'italic',
      'table',
      'list',
      'task list',
      'checkbox',
      'heading',
      'blockquote',
      'code block',
      'preview',
      'prose',
      'tiptap',
      'llm',
      'prompt',
      'tokens',
    ],
    component: lazy(() => import('./writing/visual-markdown-editor/index')),
  },
  {
    id: 'llano-castell',
    category: 'Rivers',
    title: 'Llano River @ Castell',
    description:
      'Trip planner for Kevin\'s annual Castell fishing trip. Live USGS gauge data, Castell flow estimate (no gauge there — interpolated via DAR), per-day forecast, wading verdict, and 10-year history chart.',
    keywords: [
      'llano',
      'river',
      'texas',
      'usgs',
      'gauge',
      'cfs',
      'water level',
      'castell',
      'fishing',
      'wading',
      'forecast',
      'recession',
    ],
    component: lazy(() => import('./rivers/llano-castell/index')),
  },
]

/** Unique categories in display order */
export const categories = [...new Set(tools.map((t) => t.category))]

/** Look up a tool by id */
export function getToolById(id: string): ToolDef | undefined {
  return tools.find((t) => t.id === id)
}
